### ISSUE TITLE
Miner cannot recover from   out-of-memory state

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer-miner#140]
**Describe the bug**

**To Reproduce**
1. Run miner for hours
2. Observe the miner report once in a while until find error like below

Error initialising trimmer. Aborting.
Reason: Device 1 GPUassert: out of memory mean.cu 396

**Expected behavior**
The machine setting meets the recommendation (with 8G) and miner should recover, but the miners stop working for 5 hours with zero GPS.

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware  RTX 2060 Super 8G x2
  you can paste the output of `./qitmeer-miner -l` e.g:

```
  ************** [info] # Device 0 HashRate:inf GPS **************

************** [info] # Device 0 HashRate:inf GPS **************

************** [info] # Device 0 HashRate:inf GPS **************

************** [info] # Device 0 HashRate:inf GPS **************

************** [info] # Device 0 HashRate:inf GPS **************

************** [info] # Device 0 HashRate:inf GPS **************

Reason: Device 1 GPUassert: out of memory mean.cu 396
Error initialising trimmer. Aborting.
Reason: Device 0 GPUassert: out of memory mean.cu 396
Error initialising trimmer. Aborting.


```

  ```
  $ ./qitmeer-miner --version
Qitmeer Miner Version:0.3.4(Go version go1.12.1)
  ```
- qitmeer-miner options or `.conf` file 

```
 # the miner config file

##############################
#[Necessary Config]
##############################
#
#coin
symbol=PMEER
#pow type cuckaroo|blake2bd|cuckatoo
pow=cuckaroo
#network privnet|testnet|mainnet|mixnet
network=testnet


##############################
#[Solo Config]
##############################
#miner address
#NOTE! please change to your own qitmeer addr!
mineraddress=
# node rpc server
rpcserver=http://127.0.0.1:18131
# node rpc user
rpcuser=test
# node rpc password
rpcpass=test
#not tls
notls=true
#rpccert
#rpccert=./tokyo.cert

  ```

**Additional context**

$  ./nvidia-smi.exe

```
Sun Dec 22 14:57:54 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 436.30       Driver Version: 436.30       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 206... WDDM  | 00000000:01:00.0 Off |                  N/A |
| 38%   34C    P8    19W / 175W |    223MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 206... WDDM  | 00000000:02:00.0 Off |                  N/A |
| 38%   31C    P8    12W / 175W |    183MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1296    C+G   C:\Windows\System32\LogonUI.exe            N/A      |
|    0      1304    C+G   C:\Windows\System32\dwm.exe                N/A      |
|    0      2988    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      8616    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0      9448    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0     12604      C   ...Qitmeer\qitmeer-miner\qitmeer-miner.exe N/A      |
|    1      3984    C+G   C:\Windows\System32\dwm.exe                N/A      |
|    1      8616    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    1      9180    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
|    1      9992    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
|    1     12432    C+G   C:\Windows\System32\LogonUI.exe            N/A      |
|    1     12604      C   ...Qitmeer\qitmeer-miner\qitmeer-miner.exe N/A      |
+-----------------------------------------------------------------------------+

```

**Comment by forchain** [comment]
crash on restart

```
Qitmeer@Miner ~/github.com/Qitmeer/qitmeer-miner (master*) $ ./qitmeer-miner.exe -C release-cuda.conf
2019-12-22|15:25:50.625 [INFO ] Platform:NVIDIA CUDA DeviceID:# 0 DeviceName:GeForce RTX 2060 SUPER MaxAllocSize:2048.00 MB MaxMemSize:8192.00 MB module=miner
2019-12-22|15:25:50.626 [INFO ] Platform:NVIDIA CUDA DeviceID:# 1 DeviceName:GeForce RTX 2060 SUPER MaxAllocSize:2048.00 MB MaxMemSize:8192.00 MB module=miner
2019-12-22|15:25:50.626 [INFO ] solo miner start                    module=miner
2019-12-22|15:25:50.626 [INFO ] listen submit block server          module=miner
2019-12-22|15:25:50.626 [INFO ] listen new work server              module=miner
2019-12-22|15:25:52.659 [INFO ] getBlockTemplate height:29468 , target :min difficulty 90705 module=miner
Exception 0xc0000005 0x0 0x28 0x7ffa7ccb70cc
PC=0x7ffa7ccb70cc

runtime: unknown pc 0x7ffa7ccb70cc
stack: frame={sp:0x511f988, fp:0x0} stack=[0x0,0x511fe80)
000000000511f888:  000007fe00008000  0002000000008000
000000000511f898:  0000400000010000  0000400000004000
000000000511f8a8:  0000080000008000  0000800000008000
000000000511f8b8:  0000800000000800  000007fe00008000
000000000511f8c8:  0000000000000200  0000000000000001
000000000511f8d8:  0000000000000002  0000000000000000
000000000511f8e8:  0000000100000003  00000100006ad3a8
000000000511f8f8:  0000040000400000  0000000100000001
000000000511f908:  0000000000000001  0000000000010000
000000000511f918:  0000000100010000  0000000100000000
000000000511f928:  0000002000000000  0000000000000000
000000000511f938:  0000000000000001  0000000000000000
000000000511f948:  0000000000010000  0000000000000000
000000000511f958:  0000000000000000  0000bb61f40ab13d
000000000511f968:  00007ffa7cca1c0d  0000000000000000
000000000511f978:  000000c00016c000  000000c00003fe00
000000000511f988: <00007ffa7ccb216b  0000000000000000
000000000511f998:  00007ffa7cce4ba8  0000000000000377
000000000511f9a8:  0000000000000001  0000000000000000
000000000511f9b8:  0000000000000000  0000000000000000
000000000511f9c8:  000000000511fa00  000000000044a8b7 <runtime.step+279>
000000000511f9d8:  00000000010ad9d0  0000000000000002
000000000511f9e8:  0000000000000000  8000000000000002
000000000511f9f8:  0000000000000000  0000000000002000
000000000511fa08:  0000000000449bd0 <runtime.pcvalue+352>  000000b000000000
000000000511fa18:  000000010001bc04  0000000000000000
000000000511fa28:  0000100000000000  0000008000000100
000000000511fa38:  0000040000000200  0000040000000400
000000000511fa48:  0100100000b00000  0200100000801000
000000000511fa58:  0400040004001000  206563726f466547
000000000511fa68:  3036303220585452  0000524550555320
000000000511fa78:  0000000000000000  0000000000000000
runtime: unknown pc 0x7ffa7ccb70cc
stack: frame={sp:0x511f988, fp:0x0} stack=[0x0,0x511fe80)
000000000511f888:  000007fe00008000  0002000000008000
000000000511f898:  0000400000010000  0000400000004000
000000000511f8a8:  0000080000008000  0000800000008000
000000000511f8b8:  0000800000000800  000007fe00008000
000000000511f8c8:  0000000000000200  0000000000000001
000000000511f8d8:  0000000000000002  0000000000000000
000000000511f8e8:  0000000100000003  00000100006ad3a8
000000000511f8f8:  0000040000400000  0000000100000001
000000000511f908:  0000000000000001  0000000000010000
000000000511f918:  0000000100010000  0000000100000000
000000000511f928:  0000002000000000  0000000000000000
000000000511f938:  0000000000000001  0000000000000000
000000000511f948:  0000000000010000  0000000000000000
000000000511f958:  0000000000000000  0000bb61f40ab13d
000000000511f968:  00007ffa7cca1c0d  0000000000000000
000000000511f978:  000000c00016c000  000000c00003fe00
000000000511f988: <00007ffa7ccb216b  0000000000000000
000000000511f998:  00007ffa7cce4ba8  0000000000000377
000000000511f9a8:  0000000000000001  0000000000000000
000000000511f9b8:  0000000000000000  0000000000000000
000000000511f9c8:  000000000511fa00  000000000044a8b7 <runtime.step+279>
000000000511f9d8:  00000000010ad9d0  0000000000000002
000000000511f9e8:  0000000000000000  8000000000000002
000000000511f9f8:  0000000000000000  0000000000002000
000000000511fa08:  0000000000449bd0 <runtime.pcvalue+352>  000000b000000000
000000000511fa18:  000000010001bc04  0000000000000000
000000000511fa28:  0000100000000000  0000008000000100
000000000511fa38:  0000040000000200  0000040000000400
000000000511fa48:  0100100000b00000  0200100000801000
000000000511fa58:  0400040004001000  206563726f466547
000000000511fa68:  3036303220585452  0000524550555320
000000000511fa78:  0000000000000000  0000000000000000

goroutine 7 [syscall]:
qitmeer-miner/symbols/qitmeer._Cfunc_cuda_search(0x0, 0xc0004547e0, 0xc0003e8a28, 0xc0003e8a24, 0xc0003f0630, 0xc0004788e0, 0xc0004788d8, 0xc00044b1c0, 0x0)
        _cgo_gotypes.go:65 +0x54
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine.func2(0xc0004786c0, 0xc0004547e0, 0x71, 0x11a, 0xc0003e8a28, 0x4, 0x4, 0xc0003e8a24, 0x4, 0x4, ...)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:126 +0x168
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine(0xc0004786c0, 0xc0003e8880)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:126 +0x775
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:114 +0x422

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0003e8888)
        D:/go1.12.1.windows-amd64/go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc0003e8880)
        D:/go1.12.1.windows-amd64/go/src/sync/waitgroup.go:130 +0x6c
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:146 +0x347
main.main()
        D:/miner/gosrc/src/qitmeer-miner/main.go:45 +0xe0

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        D:/go1.12.1.windows-amd64/go/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
        D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:29 +0x48

goroutine 6 [chan receive]:
main.main.func1(0xc00004e2a0)
        D:/miner/gosrc/src/qitmeer-miner/main.go:37 +0x3b
created by main.main
        D:/miner/gosrc/src/qitmeer-miner/main.go:36 +0xc3

goroutine 9 [syscall]:
qitmeer-miner/symbols/qitmeer._Cfunc_cuda_search(0x1, 0xc0003d25a0, 0xc000150bb0, 0xc000150bac, 0xc0001b40b0, 0xc000478b20, 0xc000478b18, 0xc0001587c0, 0x0)
        _cgo_gotypes.go:65 +0x54
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine.func2(0xc000478900, 0xc0003d25a0, 0x71, 0x11a, 0xc000150bb0, 0x4, 0x4, 0xc000150bac, 0x4, 0x4, ...)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:126 +0x168
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine(0xc000478900, 0xc0003e8880)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:126 +0x775
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:114 +0x422

goroutine 11 [select]:
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).ListenWork(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:157 +0x16b
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run.func2(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:122 +0x5c
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:120 +0x29f

goroutine 13 [syscall]:
qitmeer-miner/common._Cfunc_usleep(0x1312d00, 0x0)
        _cgo_gotypes.go:47 +0x50
qitmeer-miner/common.Usleep(...)
        D:/miner/gosrc/src/qitmeer-miner/common/ctimer.go:11
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Status(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:271 +0x244
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run.func4(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:134 +0x5c
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:132 +0x325

goroutine 34 [chan receive]:
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).ListenStopCuda(0xc000478900)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:209 +0x8d
created by qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:75 +0x7e

goroutine 23 [chan receive]:
qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).ListenStopCuda(0xc0004786c0)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:209 +0x8d
created by qitmeer-miner/symbols/qitmeer.(*CudaCuckaroo).Mine
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuda_cuckaroo.go:75 +0x7e

goroutine 35 [select]:
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).SubmitWork.func1(0xc0000ee000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:213 +0x143
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).SubmitWork
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:205 +0xa3

goroutine 36 [select]:
qitmeer-miner/core.(*Device).SubmitShare(0xc0004786c0, 0xc00002e1e0)
        D:/miner/gosrc/src/qitmeer-miner/core/device.go:234 +0x119
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).SubmitWork
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:258 +0x10e

goroutine 37 [select]:
qitmeer-miner/core.(*Device).SubmitShare(0xc000478900, 0xc00002e1e0)
        D:/miner/gosrc/src/qitmeer-miner/core/device.go:234 +0x119
created by qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).SubmitWork
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:258 +0x10e
rax     0x0
rbx     0xc00016bc70
rcx     0x0
rdi     0xc00016c000
rsi     0xc00003fe00
rbp     0xc00016bc30
rsp     0x511f988
r8      0x511f428
r9      0x511f501
r10     0x0
r11     0x511f5a0
r12     0xc00004bd10
r13     0xa8c3c0
r14     0xd228b8
r15     0x200
rip     0x7ffa7ccb70cc
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
Qitmeer@Miner ~/github.com/Qitmeer/qitmeer-miner (master*) $ ./qitmeer-miner.exe -C release-cuda.conf
Qitmeer@Miner ~/github.com/Qitmeer/qitmeer-miner (master*) $ history |vim -                                                            Vim: Reading from stdin...

Qitmeer@Miner ~/github.com/Qitmeer/qitmeer-miner (master*) $ vi release-cuda.conf
Qitmeer@Miner ~/github.com/Qitmeer/qitmeer-miner (master*) $
Q
```

**Comment by jamesvan2019** [comment]
reference #141

**Comment by dindinw** [comment]
@forchain Please confirm the issue has been resolved, if true, Please close the issue, thanks.
