### ISSUE TITLE
miner run error when compile self on linux

### ISSUE THREAD

**Issue by jamesvan2019** [Qitmeer/qitmeer-miner#156]
**Describe the bug**

**To Reproduce**
1. Go to compile on linux your self
2. Click on miner -l
**Screenshots (Optional)**
./qitmeer-miner -l
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xff000008 pc=0x7f79c4e22c80]

runtime stack:
runtime.throw(0xaaeb73, 0x2a)
	/root/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/root/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0x927720, 0xc000119e48, 0xc0004ee100)
	/root/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000119e18 sp=0xc000119de0 pc=0x44397b
github.com/Qitmeer/go-opencl/cl._Cfunc_clGetPlatformIDs(0x20, 0xc0004ee100, 0xc000484538, 0x0)
	_cgo_gotypes.go:828 +0x4d fp=0xc000119e48 sp=0xc000119e18 pc=0x51f85d
github.com/Qitmeer/go-opencl/cl.GetPlatforms.func1(0xc0004ee100, 0xc000484538, 0xc0000d8820)
	/root/go/pkg/mod/github.com/!qitmeer/go-opencl@v0.0.0-20190704222003-c93200893312/cl/platform.go:22 +0xcc fp=0xc000119e88 sp=0xc000119e48 pc=0x52393c
github.com/Qitmeer/go-opencl/cl.GetPlatforms(0xc000119f20, 0x47c74a, 0x11a7680, 0xc000000180, 0xc000119f50)
	/root/go/pkg/mod/github.com/!qitmeer/go-opencl@v0.0.0-20190704222003-c93200893312/cl/platform.go:22 +0x63 fp=0xc000119ef0 sp=0xc000119e88 pc=0x521c83
main.main()
	/opt/go/src/github.com/Qitmeer/qitmeer-miner/main.go:33 +0x26 fp=0xc000119f60 sp=0xc000119ef0 pc=0x9272a6
runtime.main()
	/root/go/src/runtime/proc.go:203 +0x21e fp=0xc000119fe0 sp=0xc000119f60 pc=0x47062e
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x49b911

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/root/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/root/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/root/go/src/os/signal/signal_unix.go:29 +0x41

**Additional context**

**Comment by jamesvan2019** [comment]
This problem is the static library of cuckoo error . you need compile the cuckoo-lib https://github.com/Qitmeer/cuckoo-lib.git  编译命令 cargo build --release
